spring:
  application:
    name: vmall_notification_service
  datasource:
    url: jdbc:mysql://localhost:3306/vmall_notification
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

